<?php

/**
 * @file
 * A js library to add screen touch funtions to carousels
 */
define('SWIPER_MIN_LIBRARY_VERION', '2.3');

/**
 * Implements hook_libraries_info() .
 */
function swiperjs_libraries_info() {

	$libraries['Swiper'] = array (
		'name' => 'Swiper Library',
		'vendor url' => 'http://www.idangero.us/sliders/swiper/',
		'download url' => 'https://github.com/nolimits4web/Swiper',
		'path' => 'dev',
		'version callback' => 'swiperjs_get_version',
		'version arguments' => array(
			'file' =>  'component.json',
		),
		
		'files' => array (
			'js' => array  ('dev/idangerous.swiper.js'),
			'css' => array ('dev/idangerous.swiper.css'),
		),

    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'dist/idangerous.swiper-2.3.min.js',
          ),
        ),
      ),
    ),
	
	
	);

	return $libraries;
}




/**
 *
 */
function swiperjs_get_version($library, $options)  {
	
  $file = DRUPAL_ROOT . '/' . $library['library path'] . '/' . $options['file'];
  
  if (empty($options['file']) || !file_exists($file)) {
    return;
  }
  $file = file_get_contents($file);
  $file =json_decode($file, true);
  
  if(isset($file)) {
    return $file['version'];  
  }
  
  return ;
}


